-- AlterTable
ALTER TABLE "Category" ADD COLUMN "parentId" TEXT;

-- AlterTable
ALTER TABLE "Product" ADD COLUMN "monthlySales" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Product" ADD COLUMN "salesResetAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
